/**
 * 저메추 (저녁 메뉴 추천) - 20개 메뉴 데이터셋
 * 배달 기준지: 경기도 의왕시 고천공업로 5
 */

const DELIVERY_LOCATION = {
  address: "경기도 의왕시 고천공업로 5",
  areaName: "의왕 고천공업단지 / 오전동 배달권역",
  deliveryApps: ["쿠팡이츠", "요기요"]
};

const MENU_DATA = [
  {
    id: 1,
    name: "1인 보쌈 정식",
    category: "korean",
    categoryName: "한식",
    restaurant: "싸움의고수 의왕고천점",
    calories: 780,
    price: "10,500원",
    deliveryTime: "20~35분",
    tags: ["든든한한끼", "고단백", "야근힐링"],
    description: "부드럽게 삶아낸 수육에 아삭한 무김치와 쌈채소가 어우러진 1인 가성비 정식",
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=싸움의고수+의왕고천점",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=싸움의고수+의왕고천"
  },
  {
    id: 2,
    name: "차돌 고기짬뽕 & 탕수육",
    category: "chinese",
    categoryName: "중식",
    restaurant: "홍콩반점0410 안양호계점",
    calories: 850,
    price: "13,000원",
    deliveryTime: "25~40분",
    tags: ["얼큰한국물", "스트레스해소", "불맛가득"],
    description: "진한 불향 가득한 육수에 고소한 차돌박이와 바삭 쫄깃한 찹쌀 탕수육의 환상 조합",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=홍콩반점+의왕",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=홍콩반점+호계"
  },
  {
    id: 3,
    name: "와퍼 세트 & 어니언링",
    category: "western",
    categoryName: "양식/버거",
    restaurant: "버거킹 의왕오전FS점",
    calories: 950,
    price: "9,900원",
    deliveryTime: "15~30분",
    tags: ["스피드", "육즙가득", "스테디셀러"],
    description: "직화로 구운 100% 순쇠고기 패티와 신선한 야채가 푸짐하게 들어간 버거의 정석",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=버거킹+의왕오전",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=버거킹+의왕오전"
  },
  {
    id: 4,
    name: "로제 떡볶이 & 모둠튀김",
    category: "snack",
    categoryName: "분식",
    restaurant: "배떡 의왕고천점",
    calories: 1100,
    price: "12,000원",
    deliveryTime: "25~40분",
    tags: ["꾸덕꾸덕", "당충전", "동료와함께"],
    description: "매콤하면서도 부드러운 특제 크림소스와 쫀득한 쌀떡, 바삭한 튀김이 어우러진 맛",
    image: "https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=배떡+의왕고천",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=배떡+의왕고천"
  },
  {
    id: 5,
    name: "소불고기 버섯 비빔밥",
    category: "korean",
    categoryName: "한식",
    restaurant: "본죽&비빔밥 의왕고천점",
    calories: 620,
    price: "11,000원",
    deliveryTime: "20~35분",
    tags: ["속편한한끼", "균형잡힌영양", "깔끔한맛"],
    description: "달콤 짭조름한 양념 소불고기와 신선한 제철 나물, 버섯이 듬뿍 들어간 건강 한식",
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=본죽비빔밥+의왕고천",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=본죽비빔밥+고천"
  },
  {
    id: 6,
    name: "탄단지 웜볼 & 닭가슴살 샐러드",
    category: "salad",
    categoryName: "샐러드/라이트",
    restaurant: "샐러디 의왕포일점 (고천 직배)",
    calories: 380,
    price: "8,900원",
    deliveryTime: "25~40분",
    tags: ["다이어트", "가벼운속", "저칼로리"],
    description: "닭가슴살, 고구마, 견과류와 따뜻한 곡물이 들어가 영양 밸런스를 완벽하게 맞춘 식단",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=샐러디+의왕",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=샐러디+의왕"
  },
  {
    id: 7,
    name: "프리미엄 모둠초밥 (12p)",
    category: "japanese",
    categoryName: "일식",
    restaurant: "미카도스시 안양호계/의왕점",
    calories: 580,
    price: "16,000원",
    deliveryTime: "30~45분",
    tags: ["깔끔한야식", "신선한회", "소확행"],
    description: "숙성 광어, 연어, 참치, 간장새우 등 신선한 고급 해산물로 정성껏 쥐어낸 12피스 초밥",
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=초밥+의왕고천",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=초밥+의왕고천"
  },
  {
    id: 8,
    name: "양지 차돌 쌀국수 & 짜조",
    category: "asian",
    categoryName: "아시안",
    restaurant: "하노이별 안양의왕점",
    calories: 490,
    price: "11,500원",
    deliveryTime: "20~35분",
    tags: ["따끈한강추메뉴", "해장겸식사", "가벼운포만감"],
    description: "12시간 이상 우려낸 진한 소고기 육수에 부드러운 양지 차돌과 아삭한 숙주의 조화",
    image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=쌀국수+의왕",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=쌀국수+의왕"
  },
  {
    id: 9,
    name: "양념반 후라이드반 치킨",
    category: "chicken",
    categoryName: "치킨/패스트",
    restaurant: "후라이드참잘하는집 의왕점",
    calories: 825,
    price: "16,000원",
    deliveryTime: "25~45분",
    tags: ["야근의꽃", "바삭함극치", "국민야식"],
    description: "겉은 크리스피하고 속은 촉촉한 후라이드와 매콤달콤한 비법 양념치킨의 정석 반반",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=후라이드참잘하는집+의왕",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=후참잘+의왕"
  },
  {
    id: 10,
    name: "토종 순대국밥 (얼큰/담백)",
    category: "korean",
    categoryName: "한식",
    restaurant: "백암순대국 의왕고천점",
    calories: 650,
    price: "9,000원",
    deliveryTime: "15~30분",
    tags: ["뜨끈한국밥", "직장인소울푸드", "속풀이"],
    description: "진하게 우려낸 사골 육수에 쫄깃한 토종 순대와 머릿고기가 가득 담긴 보약 같은 한 그릇",
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=순대국+의왕고천",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=백암순대국+고천"
  },
  {
    id: 11,
    name: "이탈리안 비엠티 샌드위치",
    category: "salad",
    categoryName: "샐러드/라이트",
    restaurant: "써브웨이 안양호계점 (고천 배달)",
    calories: 410,
    price: "7,800원",
    deliveryTime: "20~35분",
    tags: ["초스피드", "프레시함", "간편식"],
    description: "페퍼로니, 살라미, 햄과 신선한 야채가 듬뿍 들어가 든든하면서도 깔끔한 샌드위치",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=써브웨이+안양호계",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=써브웨이+호계"
  },
  {
    id: 12,
    name: "엽기 닭볶음탕 & 계란찜",
    category: "korean",
    categoryName: "한식",
    restaurant: "동대문엽기떡볶이 의왕점",
    calories: 1250,
    price: "24,000원",
    deliveryTime: "30~45분",
    tags: ["화끈한국물", "스트레스순삭", "팀원공유"],
    description: "칼칼하고 묵직한 국물에 부드러운 닭고기와 감자, 떡이 듬뿍 들어가 스트레스가 확 풀리는 맛",
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=동대문엽기떡볶이+의왕",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=엽기떡볶이+의왕"
  },
  {
    id: 13,
    name: "수제 흑돼지 치즈카츠",
    category: "japanese",
    categoryName: "일식",
    restaurant: "카츠공방 의왕평촌점",
    calories: 890,
    price: "13,500원",
    deliveryTime: "25~40분",
    tags: ["치즈폭포", "바삭바삭", "고급일식"],
    description: "두툼한 국내산 흑돼지 등심 속에 100% 모짜렐라 치즈가 가득 찬 프리미엄 수제 카츠",
    image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=돈까스+의왕고천",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=돈카츠+의왕"
  },
  {
    id: 14,
    name: "간장 순살 안동찜닭",
    category: "korean",
    categoryName: "한식",
    restaurant: "찜닭에반하다 의왕점",
    calories: 750,
    price: "22,000원",
    deliveryTime: "30~45분",
    tags: ["달콤짭조름", "납작당면", "밥도둑"],
    description: "특제 간장 소스에 푹 익힌 촉촉한 순살 닭고기와 쫀득한 납작당면, 감자의 완벽한 조화",
    image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=찜닭+의왕",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=찜닭+의왕"
  },
  {
    id: 15,
    name: "셀프 마라탕 (소고기+분모자)",
    category: "asian",
    categoryName: "아시안",
    restaurant: "마라공방 의왕오전점",
    calories: 720,
    price: "12,500원",
    deliveryTime: "20~35분",
    tags: ["얼얼한중독", "기분전환", "취향존중"],
    description: "알싸하고 깊은 사골 마라 육수에 소고기, 청경채, 옥수수면, 분모자가 듬뿍 들어간 마라탕",
    image: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=마라탕+의왕오전",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=마라탕+의왕"
  },
  {
    id: 16,
    name: "카라이 마제소바 & 미니밥",
    category: "japanese",
    categoryName: "일식",
    restaurant: "킨토토 안양평촌점 (의왕 배달)",
    calories: 790,
    price: "10,500원",
    deliveryTime: "25~40분",
    tags: ["비빔라멘", "감칠맛폭발", "별미"],
    description: "특제 고기 고명과 부추, 대파, 노른자를 비벼먹는 나고야식 비빔 라멘 (밥 비벼먹기 필수)",
    image: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=마제소바+안양",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=마제소바+의왕"
  },
  {
    id: 17,
    name: "직화 매콤 삼겹덮밥",
    category: "korean",
    categoryName: "한식",
    restaurant: "덮밥슈퍼 의왕점",
    calories: 710,
    price: "9,500원",
    deliveryTime: "20~35분",
    tags: ["직화불맛", "혼밥추천", "간편든든"],
    description: "불맛 가득 직화로 구워낸 매콤한 삼겹살과 볶음김치, 계란후라이가 올라간 든든한 덮밥",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=덮밥+의왕",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=덮밥+의왕"
  },
  {
    id: 18,
    name: "신선 한우 육회비빔밥",
    category: "korean",
    categoryName: "한식",
    restaurant: "뱃놈과백정 의왕고천점",
    calories: 590,
    price: "12,000원",
    deliveryTime: "20~35분",
    tags: ["신선보장", "프리미엄한식", "고급단백질"],
    description: "신선한 당일 도축 생육회에 특제 고추장 소스와 신선한 새싹채소를 비벼먹는 별미 한식",
    image: "https://images.unsplash.com/photo-1553163147-622ab57be1c7?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=육회비빔밥+의왕고천",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=육회비빔밥+고천"
  },
  {
    id: 19,
    name: "매운 우삼겹 크림 파스타",
    category: "western",
    categoryName: "양식/버거",
    restaurant: "롤링파스타 안양범계점 (고천 배달)",
    calories: 820,
    price: "9,900원",
    deliveryTime: "25~40분",
    tags: ["매콤크림", "가성비파스타", "양식힐링"],
    description: "부드럽고 진한 크림소스에 청양고추의 매콤함과 고소한 우삼겹이 어우러진 시그니처 파스타",
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281691?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=롤링파스타+안양",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=파스타+의왕고천"
  },
  {
    id: 20,
    name: "제육볶음 푸짐 한상 도시락",
    category: "korean",
    categoryName: "한식",
    restaurant: "든든도시락 의왕공단점",
    calories: 730,
    price: "8,500원",
    deliveryTime: "15~25분",
    tags: ["공단맞춤", "초스피드배달", "가성비갑"],
    description: "불맛 입힌 매콤 제육볶음과 계란말이, 계절 반찬 4종, 따끈한 국물로 구성된 공단 인기 도시락",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    coupangUrl: "https://web.coupangeats.com/search?q=도시락+의왕고천",
    yogiyoUrl: "https://www.yogiyo.co.kr/mobile/#/search/?keyword=도시락+의왕공업로"
  }
];
